### ISSUE TITLE
Waiting for WiFi connect does not delay due to missing braces.

### ISSUE THREAD

**Issue by AlanKilian** [TinyCircuits/TinyCircuits-TinyShield-WiFi-ATWINC1500-ASD2123#1]
Missing braces for control structure.

  while (WiFi.status() != WL_CONNECTED)
    Serial.print(".");
    delay(500);

should be:
  while (WiFi.status() != WL_CONNECTED) {
    Serial.print(".");
    delay(500);
  }

Using whatever your braces standards are.

**Comment by TinyCircuits** [comment]
Fixed the brackets!

Good catch!
